# Generated by Django 4.0.1 on 2022-05-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PensionCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('registration_number', models.TextField()),
                ('lot_number_address', models.TextField()),
                ('road_name_address', models.TextField()),
                ('employees_count', models.IntegerField()),
                ('data_created_at', models.CharField(max_length=7)),
            ],
            options={
                'verbose_name': 'PensionCompany',
                'verbose_name_plural': 'PensionCompanies',
            },
        ),
    ]
